#############################
#############################

## RPECK 13/07/2023 - Github Action
## This is used to deploy builds of our child theme (firstly to the added sites and then to Wordpress SVN respository)
## https://docs.github.com/en/actions/learn-github-actions/expressions#fromjson

#############################
#############################

## Deploy the sites to the various endpoints
name: Deploy to stored FTP sites

## On push
on:
  push:
    branches:
      - 'main'
      - 'releases/**'

# Jobs
jobs:

  ###############
  ## RPECK 16/07/2023 - Matrix of FTP accounts
  ## This is used to give us the means to collate different endpoints to which we can deploy our theme
  matrix:
  
    # OS
    runs-on: ubuntu-latest

    # Outputs 
    outputs: 
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    # Steps
    steps:

      - id: set-matrix
        run: echo "matrix=[{\"host\":\"ftp.parishframework3.actondev7.com\",\"user\":\"deploy@parishframework3.actondev7.com\",\"pass\":\"jwrn)U-jG5MP\",\"directory\":\"./public_html/wp-content/themes/kadence-child-theme/\"}]" >> $GITHUB_OUTPUT

  ###############
  ## RPECK 16/07/2023 - Deploy
  ## This is presently limited to the single item  
  deploy:

    # OS
    runs-on: ubuntu-latest 

    # Needs 
    needs: matrix 

    # Strategy
    # This pulls in the value from the initial matrix job
    strategy:
      matrix:
        include: ${{ fromJSON(needs.matrix.outputs.matrix) }}

    # Steps
    ## Each of these steps are run for the various FTP credentials we have inferred from the matrix variable above
    steps:

      - name: 🚚 Get latest code
        uses: actions/checkout@v3
      
      - name: 📂 Sync files
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ${{ matrix.host }}
          user: ${{ matrix.user }}
          password: ${{ matrix.pass }}
          remoteDir: ${{ matrix.directory }}
          options: "--delete --asci"